services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: cybermapp-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-cybermapp.alwaysdata.net
      PMA_PORT: 3306
      PMA_USER: cybermapp
      PMA_PASSWORD: momoafec64
    ports:
      - "8080:80"